/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaconnect;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author danis
 */
public class pos1 extends javax.swing.JFrame {
    
    Connection conn= null;
    ResultSet rs =null;
    PreparedStatement pst = null;
    
    int orderNum=0;
    String userName = NewJFrame.getUserName();
    String itemName = null;
    double price=0.0;
    int index=0;
    double [] priceArray = new double [20];
    public static double arrayTotal=0;
    public static double tax=0;
    public static double grandTotal=0;
    public static double discountedAmount=0;
    NumberFormat formatter = NumberFormat.getCurrencyInstance(); 
    
    public pos1() {
        initComponents();
        conn =NewJFrame.ConnecrDb();
        double price=0.0;
        header();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        showUser1 = new javax.swing.JLabel();
        dateHeader1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        coffee = new javax.swing.JButton();
        doug = new javax.swing.JButton();
        tea = new javax.swing.JButton();
        burger = new javax.swing.JButton();
        omelette = new javax.swing.JButton();
        muffin = new javax.swing.JButton();
        smoothie = new javax.swing.JButton();
        fries = new javax.swing.JButton();
        ice = new javax.swing.JButton();
        chocolate = new javax.swing.JButton();
        pop = new javax.swing.JButton();
        hot = new javax.swing.JButton();
        soup = new javax.swing.JButton();
        croissant = new javax.swing.JButton();
        pizza = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reciept = new javax.swing.JTextArea();
        grant = new javax.swing.JTextField();
        runningTax = new javax.swing.JTextField();
        runningTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        couponField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        discountField = new javax.swing.JTextField();

        showUser.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        showUser.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(58, 58, 58));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jButton22.setBackground(new java.awt.Color(204, 0, 51));
        jButton22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Log out");
        jButton22.setToolTipText("");
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        jButton22.setFocusPainted(false);
        jButton22.setFocusable(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        showUser1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        showUser1.setForeground(new java.awt.Color(255, 255, 255));

        dateHeader1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dateHeader1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(dateHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jScrollPane1.setViewportView(jTextPane1);

        jPanel3.setBackground(new java.awt.Color(48, 48, 48));

        coffee.setBackground(new java.awt.Color(204, 153, 0));
        coffee.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        coffee.setForeground(new java.awt.Color(0, 0, 0));
        coffee.setText("Coffee");
        coffee.setBorder(null);
        coffee.setBorderPainted(false);
        coffee.setFocusPainted(false);
        coffee.setFocusable(false);
        coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeActionPerformed(evt);
            }
        });

        doug.setBackground(new java.awt.Color(204, 153, 0));
        doug.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        doug.setForeground(new java.awt.Color(0, 0, 0));
        doug.setText("Doughnut");
        doug.setBorder(null);
        doug.setBorderPainted(false);
        doug.setFocusPainted(false);
        doug.setFocusable(false);
        doug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dougActionPerformed(evt);
            }
        });

        tea.setBackground(new java.awt.Color(204, 0, 51));
        tea.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        tea.setForeground(new java.awt.Color(0, 0, 0));
        tea.setText("Tea");
        tea.setBorder(null);
        tea.setBorderPainted(false);
        tea.setFocusPainted(false);
        tea.setFocusable(false);
        tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaActionPerformed(evt);
            }
        });

        burger.setBackground(new java.awt.Color(0, 153, 0));
        burger.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        burger.setForeground(new java.awt.Color(0, 0, 0));
        burger.setText("Burger");
        burger.setBorder(null);
        burger.setBorderPainted(false);
        burger.setFocusPainted(false);
        burger.setFocusable(false);
        burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerActionPerformed(evt);
            }
        });

        omelette.setBackground(new java.awt.Color(204, 102, 0));
        omelette.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        omelette.setForeground(new java.awt.Color(0, 0, 0));
        omelette.setText("omelette");
        omelette.setToolTipText("");
        omelette.setBorder(null);
        omelette.setBorderPainted(false);
        omelette.setFocusPainted(false);
        omelette.setFocusable(false);
        omelette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                omeletteActionPerformed(evt);
            }
        });

        muffin.setBackground(new java.awt.Color(204, 0, 51));
        muffin.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        muffin.setForeground(new java.awt.Color(0, 0, 0));
        muffin.setText("Muffin");
        muffin.setBorder(null);
        muffin.setBorderPainted(false);
        muffin.setFocusPainted(false);
        muffin.setFocusable(false);
        muffin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muffinActionPerformed(evt);
            }
        });

        smoothie.setBackground(new java.awt.Color(204, 102, 0));
        smoothie.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        smoothie.setForeground(new java.awt.Color(0, 0, 0));
        smoothie.setText("Smoothie");
        smoothie.setBorder(null);
        smoothie.setBorderPainted(false);
        smoothie.setFocusPainted(false);
        smoothie.setFocusable(false);
        smoothie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smoothieActionPerformed(evt);
            }
        });

        fries.setBackground(new java.awt.Color(0, 153, 0));
        fries.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        fries.setForeground(new java.awt.Color(0, 0, 0));
        fries.setText("Fries");
        fries.setBorder(null);
        fries.setBorderPainted(false);
        fries.setFocusPainted(false);
        fries.setFocusable(false);
        fries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friesActionPerformed(evt);
            }
        });

        ice.setBackground(new java.awt.Color(204, 153, 0));
        ice.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        ice.setForeground(new java.awt.Color(0, 0, 0));
        ice.setText("Ice Cream");
        ice.setBorder(null);
        ice.setBorderPainted(false);
        ice.setFocusPainted(false);
        ice.setFocusable(false);
        ice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iceActionPerformed(evt);
            }
        });

        chocolate.setBackground(new java.awt.Color(204, 102, 0));
        chocolate.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        chocolate.setForeground(new java.awt.Color(0, 0, 0));
        chocolate.setText("Chocolate");
        chocolate.setBorder(null);
        chocolate.setBorderPainted(false);
        chocolate.setFocusPainted(false);
        chocolate.setFocusable(false);
        chocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolateActionPerformed(evt);
            }
        });

        pop.setBackground(new java.awt.Color(0, 153, 0));
        pop.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        pop.setForeground(new java.awt.Color(0, 0, 0));
        pop.setText("Pop");
        pop.setBorder(null);
        pop.setBorderPainted(false);
        pop.setFocusPainted(false);
        pop.setFocusable(false);
        pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popActionPerformed(evt);
            }
        });

        hot.setBackground(new java.awt.Color(204, 0, 51));
        hot.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        hot.setForeground(new java.awt.Color(0, 0, 0));
        hot.setText("Hot dog");
        hot.setBorder(null);
        hot.setBorderPainted(false);
        hot.setFocusPainted(false);
        hot.setFocusable(false);
        hot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotActionPerformed(evt);
            }
        });

        soup.setBackground(new java.awt.Color(30, 144, 255));
        soup.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        soup.setForeground(new java.awt.Color(0, 0, 0));
        soup.setText("Soup");
        soup.setBorder(null);
        soup.setBorderPainted(false);
        soup.setFocusPainted(false);
        soup.setFocusable(false);
        soup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soupActionPerformed(evt);
            }
        });

        croissant.setBackground(new java.awt.Color(30, 144, 255));
        croissant.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        croissant.setForeground(new java.awt.Color(0, 0, 0));
        croissant.setText("Croissant");
        croissant.setBorder(null);
        croissant.setBorderPainted(false);
        croissant.setFocusPainted(false);
        croissant.setFocusable(false);
        croissant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croissantActionPerformed(evt);
            }
        });

        pizza.setBackground(new java.awt.Color(30, 144, 255));
        pizza.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        pizza.setForeground(new java.awt.Color(0, 0, 0));
        pizza.setText("Pizza");
        pizza.setBorder(null);
        pizza.setBorderPainted(false);
        pizza.setFocusPainted(false);
        pizza.setFocusable(false);
        pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(coffee, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doug, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ice, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tea, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(muffin, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hot, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(burger, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smoothie, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(omelette, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(fries, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pop, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(soup, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(croissant, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coffee, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doug, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tea, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(muffin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hot, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burger, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fries, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pop, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smoothie, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(omelette, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soup, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(croissant, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(48, 48, 48));

        jButton17.setBackground(new java.awt.Color(204, 204, 204));
        jButton17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 0, 0));
        jButton17.setText("Cancel");
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.setFocusPainted(false);
        jButton17.setFocusable(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(204, 204, 204));
        jButton18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 0, 0));
        jButton18.setText("Void");
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.setFocusPainted(false);
        jButton18.setFocusable(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(204, 204, 204));
        jButton19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 0, 0));
        jButton19.setText("Coupons");
        jButton19.setToolTipText("");
        jButton19.setBorder(null);
        jButton19.setBorderPainted(false);
        jButton19.setFocusPainted(false);
        jButton19.setFocusable(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(204, 204, 204));
        jButton23.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton23.setForeground(new java.awt.Color(0, 0, 0));
        jButton23.setText("Add");
        jButton23.setBorder(null);
        jButton23.setBorderPainted(false);
        jButton23.setFocusPainted(false);
        jButton23.setFocusable(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(204, 204, 204));
        jButton16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 0, 0));
        jButton16.setText("Place");
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.setFocusPainted(false);
        jButton16.setFocusable(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        reciept.setBackground(new java.awt.Color(255, 255, 255));
        reciept.setColumns(20);
        reciept.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        reciept.setForeground(new java.awt.Color(0, 0, 0));
        reciept.setRows(5);
        reciept.setBorder(null);
        reciept.setFocusable(false);
        jScrollPane2.setViewportView(reciept);

        grant.setBackground(new java.awt.Color(48, 48, 48));
        grant.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        grant.setForeground(new java.awt.Color(255, 255, 255));
        grant.setBorder(null);
        grant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grantActionPerformed(evt);
            }
        });

        runningTax.setBackground(new java.awt.Color(48, 48, 48));
        runningTax.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        runningTax.setForeground(new java.awt.Color(255, 255, 255));
        runningTax.setBorder(null);
        runningTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runningTaxActionPerformed(evt);
            }
        });

        runningTotal.setBackground(new java.awt.Color(48, 48, 48));
        runningTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        runningTotal.setForeground(new java.awt.Color(255, 255, 255));
        runningTotal.setBorder(null);
        runningTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runningTotalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sub total");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tax");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Grand total");

        couponField.setBackground(new java.awt.Color(48, 48, 48));
        couponField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        couponField.setForeground(new java.awt.Color(255, 255, 255));
        couponField.setBorder(null);
        couponField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couponFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Discount ");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Coupon");

        discountField.setBackground(new java.awt.Color(48, 48, 48));
        discountField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        discountField.setForeground(new java.awt.Color(255, 255, 255));
        discountField.setBorder(null);
        discountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(grant, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(runningTax, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(couponField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(runningTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(runningTax, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(runningTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grant, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(couponField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dougActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dougActionPerformed
     itemName ="Doughnut";
     price=1.75;
     index=1;
    }//GEN-LAST:event_dougActionPerformed

    private void iceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iceActionPerformed
     itemName ="Ice Cream";
     price=4.25;
     index=2;
    }//GEN-LAST:event_iceActionPerformed

    private void coffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeActionPerformed
     itemName ="Coffee";
     price=2.25;
     index=0;
    }//GEN-LAST:event_coffeeActionPerformed

    private void smoothieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smoothieActionPerformed
     itemName ="Smoothie";
     price=4.75;
     index=9;
    }//GEN-LAST:event_smoothieActionPerformed

    private void teaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaActionPerformed
     itemName ="Tea";
     price=2.25;
     index=3;
    }//GEN-LAST:event_teaActionPerformed

    private void burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerActionPerformed
     itemName ="Burger";
     price=5.75;
     index=6;
    }//GEN-LAST:event_burgerActionPerformed

    private void friesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friesActionPerformed
     itemName ="Fries";
     price=3.55;
     index=7;
    }//GEN-LAST:event_friesActionPerformed

    private void omeletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_omeletteActionPerformed
     itemName ="Omelette";
     price=4.55;
     index=10;
    }//GEN-LAST:event_omeletteActionPerformed

    private void muffinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muffinActionPerformed
    itemName ="Muffin";
     price=1.65;
     index=4;
    }//GEN-LAST:event_muffinActionPerformed

    private void chocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolateActionPerformed
     itemName ="Chocolate";
     price=1.55;
     index=11;
    }//GEN-LAST:event_chocolateActionPerformed

    private void popActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popActionPerformed
     itemName ="Pop";
     price=1.15;
     index=8;
    }//GEN-LAST:event_popActionPerformed

    private void hotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotActionPerformed
    itemName ="Hot Dog";
     price=3.25;
     index=5;
    }//GEN-LAST:event_hotActionPerformed

    private void soupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soupActionPerformed
     itemName ="Soup";
     price=4.75;
     index=12;
    }//GEN-LAST:event_soupActionPerformed

    private void croissantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croissantActionPerformed
    itemName ="Croissant";
     price=2.35;
     index=13;
    }//GEN-LAST:event_croissantActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
     
        if(coupons.discountedpercentage>0)
        {
            pos1.updateAmount();
        }
        
        if(grandTotal>0)
        {  
        reciept.append("\nTotal = " + grant.getText());
        reciept.append("\nTax = " + runningTax.getText());
        reciept.append("\nSub total = " + runningTotal.getText());
        
                String sql = "INSERT INTO sales (SubTotal ,Tax,GrandTotal) VALUES(?,?,?)";
                try
                {
                    pst = conn.prepareStatement(sql);
                    pst.setString(1,grant.getText());
                    pst.setString(2,runningTax.getText());
                    pst.setString(3,runningTotal.getText()); 
                    pst.execute();
                    pst.close();
                    rs.close();
                }
                catch(Exception e)
                {  
                }
                  
                    String sql5 = "SELECT id FROM sales ORDER BY id DESC LIMIT 1";
                try
                    {
                        pst = conn.prepareStatement(sql5);
                        rs=pst.executeQuery();
                        orderNum=rs.getInt("id");  
                   }
                catch(Exception e)
                    {

                    }
                reciept.append("\n\nOrder number = " + orderNum);
                reciept.append("\n\nThanks, have a wonderful day");
        
                String sql2 = "INSERT INTO items (OrderNumber,Coffee,Doug,Ice,Tea,Muffin,Hot,Burger,Fries,Pop,Smooth,Oml,Choc,Soup,Crois,Pizza) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                try
                {
                    pst = conn.prepareStatement(sql2);
                    pst.setInt(1, orderNum);
                    pst.setString(2,String.valueOf(priceArray[0]));
                    pst.setString(3,String.valueOf(priceArray[1]));
                    pst.setString(4,String.valueOf(priceArray[2])); 
                    pst.setString(5,String.valueOf(priceArray[3]));
                    pst.setString(6,String.valueOf(priceArray[4]));
                    pst.setString(7,String.valueOf(priceArray[5])); 
                    pst.setString(8,String.valueOf(priceArray[6]));
                    pst.setString(9,String.valueOf(priceArray[7]));
                    pst.setString(10,String.valueOf(priceArray[8])); 
                    pst.setString(11,String.valueOf(priceArray[9]));
                    pst.setString(12,String.valueOf(priceArray[10]));
                    pst.setString(13,String.valueOf(priceArray[11])); 
                    pst.setString(14,String.valueOf(priceArray[12]));
                    pst.setString(15,String.valueOf(priceArray[13]));
                    pst.setString(16,String.valueOf(priceArray[14])); 
                    pst.execute();
                    pst.close();
                    rs.close();
                }
                catch(Exception e)
                {
                }
             String timeStamps = new SimpleDateFormat("                              yyyy.MM.dd \n").format(new Date());
             String sql3 = "INSERT INTO date (OrderNum,Dates) VALUES(?,?)";
                try
                {
                    pst = conn.prepareStatement(sql3);
                    pst.setInt(1, orderNum);
                    pst.setString(2,timeStamps);
                    pst.execute();
                    pst.close();
                    rs.close();
                }
                catch(Exception e)
                {
                }
                String sql4 = "INSERT INTO employee (OrderNum,name) VALUES(?,?)";
                try
                {
                    pst = conn.prepareStatement(sql4);
                    pst.setInt(1, orderNum);
                    pst.setString(2,userName);
                    pst.execute();
                    JOptionPane.showMessageDialog(null,"Order has been placed");
                    pst.close();
                    rs.close();
                }
                catch(Exception e)
                {
                }
             try 
             {
              pos1.reciept.print();
             } 
             catch (PrinterException ex) 
             {
              Logger.getLogger(pos1.class.getName()).log(Level.SEVERE, null, ex);
             }
            header();
            itemName =null;
            price=0;
            arrayTotal=0;
            tax=0;
            grandTotal=0;
            grant.setText(null);
            runningTax.setText(null);
            runningTotal.setText(null);
            couponField.setText(null);
            discountField.setText(null);
            Arrays.fill(priceArray,0);
            coupons.discountedpercentage=0;
            discountedAmount=0;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Cart is empty!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
    header();
    itemName =null;
    price=0;
    arrayTotal=0;
    tax=0;
    grandTotal=0;
    header();
    grant.setText(null);
    runningTax.setText(null);
    runningTotal.setText(null);
    couponField.setText(null);
    discountField.setText(null);
    Arrays.fill(priceArray,0);
    discountedAmount=0;
    coupons.discountedpercentage=0;
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        
        
        if(priceArray[index]==0)
        {
            if(price==0)
            {
             JOptionPane.showMessageDialog(this, "Please choose an item to void!", "ERROR", JOptionPane.ERROR_MESSAGE);   
            }
            else
            {
             JOptionPane.showMessageDialog(this, "Item is not in the cart!", "ERROR", JOptionPane.ERROR_MESSAGE);   
            }
        }
        else
        {
        reciept.append("Removing              " + itemName+"      $"+String.valueOf(price)+"\n");
        priceArray[index]-=price;
        arrayTotal=arraySum(priceArray);
        tax = calculateHST(arrayTotal);
        grandTotal=arrayTotal+tax;
        grant.setText(formatter.format(arrayTotal));
        runningTax.setText(formatter.format(tax));
        runningTotal.setText(formatter.format(grandTotal));
        price=0;
        itemName=null;
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
     if(coupons.discountedpercentage>0)
     {
      JOptionPane.showMessageDialog(this, "You can only apply one coupon!", "ERROR", JOptionPane.ERROR_MESSAGE);   
     }
     if(grandTotal>0 && coupons.discountedpercentage==0)
     {
       coupons window = new coupons();
       window.setVisible(true);
     }
     if(grandTotal==0)
     {
          JOptionPane.showMessageDialog(this, "Cart is empty!", "ERROR", JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaActionPerformed
     itemName ="Pizza Slice";
     price=3.15;
     index=14;
    }//GEN-LAST:event_pizzaActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
     if(price!=0)
     {
        reciept.append("                              " + itemName+"      $"+String.valueOf(price)+"\n");
        priceArray[index]+=price;
        arrayTotal=arraySum(priceArray);
        tax = calculateHST(arrayTotal);
        grant.setText(formatter.format(arrayTotal));
        runningTax.setText(formatter.format(tax));
        grandTotal=arrayTotal+tax;
        runningTotal.setText(formatter.format(grandTotal));
        price=0;
        itemName=null;
        index=16;
     }
             
    }//GEN-LAST:event_jButton23ActionPerformed

    private void grantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grantActionPerformed

    private void runningTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runningTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runningTaxActionPerformed

    private void runningTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runningTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runningTotalActionPerformed

    private void couponFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couponFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_couponFieldActionPerformed

    private void discountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountFieldActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        setVisible(false);
        NewJFrame window = new NewJFrame();
        window.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
            
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pos1().setVisible(true);
            }
        });
    }
    public void header ()
    {
        String timeStamps = new SimpleDateFormat("                              yyyy.MM.dd  hh.mm a \n").format(new Date());
        dateHeader1.setText(timeStamps);
        showUser1.setText("Hello, " + userName);
        reciept.setText(null);
        reciept.append("                              **THE COFFEE CLUB**\n");
        reciept.append("           **230 Dundas Street, London, ON, N6B 2H6**\n");
        reciept.append("           ** Phone:226-700-9229 | www.thecoffeeclub.ca **\n");
        String timeStamp = new SimpleDateFormat("                              yyyy.MM.dd  hh.mm a \n").format(new Date());
        reciept.append(timeStamp);
        reciept.append("    *******************************************************   \n");
    }
    
    public static double arraySum(double [] doubleArray)
    {
        double runningTotal=0;
        for(int index=0;index<doubleArray.length;index++)
        {
          runningTotal+=doubleArray[index];    
        }
        return runningTotal;
    }
    
    public static double calculateHST(double price)	
    {
            final double HST_TAX=0.13;// Create a constant for the HST.
            double tax= price* HST_TAX;//Calculating the HST and storing it to a variable.
            tax*=100;// multiply the tax by 100 to move its decimal point two places to the right.
            tax+=0.05;//done for rounding purposes. Mike clarkson's approach.
            int temp= (int)tax;//create a temporary int variable to store the casted version
            tax=(double)temp/100;//now divide the temp value by 100 to move it two places back to the left
            return tax;
    }
    public static String orderNumber()
    {
        UUID uniqueKey  = UUID.randomUUID();
        String orderNumber=uniqueKey.toString();
        return orderNumber;
    }
    public static void updateAmount()
    {
        NumberFormat formatter = NumberFormat.getCurrencyInstance();
        discountedAmount= (arrayTotal* coupons.discountedpercentage)/100.0;
        couponField.setText(coupons.discountedpercentage + "% " );
        discountField.setText(formatter.format(discountedAmount));
        arrayTotal-=discountedAmount;
        tax = calculateHST(arrayTotal);
        grandTotal=arrayTotal+tax;
        grant.setText(formatter.format(arrayTotal));
        runningTax.setText(formatter.format(tax));
        runningTotal.setText(formatter.format(grandTotal));
        pos1.reciept.append("\n**Coupon applied | "+ coupons.discountedpercentage + "% |" +formatter.format (discountedAmount)+"\n" );
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton burger;
    private javax.swing.JButton chocolate;
    private javax.swing.JButton coffee;
    public static javax.swing.JTextField couponField;
    private javax.swing.JButton croissant;
    private javax.swing.JLabel dateHeader1;
    public static javax.swing.JTextField discountField;
    private javax.swing.JButton doug;
    private javax.swing.JButton fries;
    public static javax.swing.JTextField grant;
    private javax.swing.JButton hot;
    private javax.swing.JButton ice;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton muffin;
    private javax.swing.JButton omelette;
    private javax.swing.JButton pizza;
    private javax.swing.JButton pop;
    public static javax.swing.JTextArea reciept;
    public static javax.swing.JTextField runningTax;
    public static javax.swing.JTextField runningTotal;
    private javax.swing.JLabel showUser;
    private javax.swing.JLabel showUser1;
    private javax.swing.JButton smoothie;
    private javax.swing.JButton soup;
    private javax.swing.JButton tea;
    // End of variables declaration//GEN-END:variables
}
